server:
  port: 8080
spring:
  application:
    name: "autentication-services"
  r2dbc:
    host: localhost
    port: 5432
    database: crediya_authentication
    schema: public
    username: jhompo
    password: pass123
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
